AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  wisesayings-app

  Sample SAM Template for wisesayings-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  WiseSayingsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - cloudwatch:*
              - events:*
              - dynamodb:*
              - lambda:*
              - logs:*
              - sns:*
              - s3:*
            Resource: '*'
      CodeUri: source/
      Handler: index_update.handler
      Runtime: nodejs8.10
      Environment:
        Variables:
          NOTIFICATION_TOPIC_ARN: 'arn:aws:sns:us-west-1:451111272122:sayingsTopicTwo'
      Events:
        WiseSayings:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /wisesayings
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  WiseSayingsApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/wisesayings"
  WiseSayingsFunction:
    Description: "Wise Sayings Lambda Function ARN"
    Value: !GetAtt WiseSayingsFunction.Arn
  WiseSayingsFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt WiseSayingsFunctionRole.Arn
